namespace: course-staging
nameSuffix: -staging
resources:
  - ../base
patches:
  - path: patch-deployment.yml
configMapGenerator:
  - name: course-reservations-config
    behavior: merge
    literals:
      - APP_ENVIRONMENT=staging
