apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-reservations
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: app
          image: ghcr.io/podzimekmartin/www3:staging
