apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-reservations
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: app
          image: ghcr.io/podzimekmartin/www3:canary
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
